# Generated by Django 5.2.6 on 2025-09-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilteredPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offensive_phrase', models.CharField(help_text='The disrespectful word or phrase.', max_length=255, unique=True)),
                ('polite_suggestion', models.CharField(help_text='The respectful alternative to suggest.', max_length=255)),
                ('language', models.CharField(choices=[('en', 'English'), ('ml', 'Malayalam'), ('hi', 'Hindi')], default='en', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['offensive_phrase'],
            },
        ),
    ]
