# Generated by Django 5.2.6 on 2025-09-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_filteredphrase_polite_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcribed_text', models.TextField(help_text='The original text that was spoken.')),
                ('polite_suggestion', models.TextField(help_text='The AI-generated polite suggestion.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
