# Generated by Django 5.2.6 on 2025-09-19 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_analysisreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisReport',
        ),
    ]
